robot:
  conn_type: "ap"        # โหมด Wi-Fi Direct (สลับเป็น "usb" ได้ในแลปถัดไปเพื่อวัด Latency)
  tile_size: 0.37   # ระยะทางต่อ 1 ช่องกระเบื้อง (เมตร)
  speed: 0.6           # ความเร็วการเคลื่อนที่ (เมตร/วินาที)
  sample_freq: 10        # ความถี่ในการเก็บข้อมูลเซนเซอร์ (Hz)